export const ACTION_TYPES = {
  CLICK_SEARCH: "CLICK_SEARCH",
  CLICK_OUTSIDE: "CLICK_OUTSIDE",
  ON_WRITING: "ON_WRITING",
  ENTER_SEARCH: "ENTER_SEARCH",
  ADD_SEARCH_CHIP: "ADD_SEARCH_CHIP",
  REMOVE_SEARCH_CHIP: "REMOVE_SEARCH_CHIP",
  CHOOSE_SEARCH_FROM: "CHOOSE_SEARCH_FROM",
  CLOSE_FLOATING_INPUT: "CLOSE_FLOATING_INPUT",
}